import Link from "next/link";
import { useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { usePreferences } from "@/context/PreferencesContext";
import { platformRequest } from "@/services/api";
import Workspace, { Resource, useResource, Empty, Pager, ConfirmDialog, displayDate } from "./Workspace";
import { Metric, Filters, History } from "./UserWorkspace";

export function AdminOverview() {
  const state = useResource("/admin/overview"), { t } = usePreferences();
  return <Workspace admin title="admin.title"><p className="muted">{t("admin.anonymous")}</p><Resource state={state}>{data => <div className="metric-grid">{Object.entries(data).map(([key, value]) => <Metric key={key} label={t(`admin.${key}`)} value={value} />)}</div>}</Resource></Workspace>;
}
function Users() {
  const { t, language } = usePreferences(), { user } = useAuth(), [page, setPage] = useState(1), [filters, setFilters] = useState({}), [change, setChange] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(false);
  const state = useResource(`/admin/users?${new URLSearchParams({ ...filters, page, limit: 10 })}`);
  async function update() { setBusy(true); setError(false); try { await platformRequest(`/admin/users/${encodeURIComponent(change.uid)}`, { method: "PATCH", body: change.values }); setChange(null); state.reload(); } catch { setError(true); } finally { setBusy(false); } }
  return <Workspace admin title="admin.users"><Filters users apply={value => { setFilters(value); setPage(1); }} /><Resource state={state}>{data => <>{data.items.length ? <div className="table-scroll"><table><caption className="visually-hidden">{t("admin.users")}</caption><thead><tr>{["account.email", "admin.role", "admin.status", "dash.date", "admin.action"].map(k => <th key={k}>{t(k)}</th>)}</tr></thead><tbody>{data.items.map(row => <tr key={row.uid}><td className="identity-label">{row.email}<br /><span className="muted">{row.displayName}</span></td><td>{t(row.role === "ADMIN" ? "dash.adminRole" : "dash.user")}</td><td>{t(row.isActive ? "admin.active" : "admin.inactive")}</td><td>{displayDate(row.createdAt, language)}</td><td>{row.uid === user?.uid ? t("admin.self") : <div className="table-actions"><button className="btn btn-secondary" onClick={() => setChange({ uid: row.uid, email: row.email, values: { role: row.role === "ADMIN" ? "USER" : "ADMIN" } })}>{t(row.role === "ADMIN" ? "admin.demote" : "admin.promote")}</button><button className="btn btn-secondary" onClick={() => setChange({ uid: row.uid, email: row.email, values: { isActive: !row.isActive } })}>{t(row.isActive ? "admin.disable" : "admin.enable")}</button></div>}</td></tr>)}</tbody></table></div> : <Empty />}<Pager data={data} setPage={setPage} /></>}</Resource><ConfirmDialog open={!!change} busy={busy} title="admin.changeTitle" description="admin.changeHint" onConfirm={update} onCancel={() => { setChange(null); setError(false); }}><p className="identity-label">{change?.email} → {change?.values.role ? t(change.values.role === "ADMIN" ? "dash.adminRole" : "dash.user") : t(change?.values.isActive ? "admin.active" : "admin.inactive")}</p>{error && <p role="alert">{t("admin.changeError")}</p>}</ConfirmDialog></Workspace>;
}
function Analytics() {
  const state = useResource("/admin/analytics"), { t } = usePreferences();
  return <Workspace admin title="admin.analytics"><p className="muted">{t("admin.period")}</p><Resource state={state}>{data => <div className="analytics-grid">{["daily", "languages", "conditions", "risks", "users"].map(key => <section className="card" key={key}><h2>{t(key === "users" ? "admin.usersChart" : `admin.${key}`)}</h2>{!data[key]?.length ? <Empty /> : <ul className="count-chart">{data[key].map(row => <li key={row._id}><div><span>{key === "risks" ? t(row._id === "UNAVAILABLE" ? "result.riskUnavailable" : `risk.${row._id?.toLowerCase()}`) : key === "languages" ? t(row._id === "bn" ? "pref.bangla" : "pref.english") : row._id || "—"}</span><strong>{row.count}</strong></div><span className="count-track" aria-hidden="true"><span style={{ width: `${100 * row.count / Math.max(1, ...data[key].map(v => v.count))}%` }} /></span></li>)}</ul>}</section>)}</div>}</Resource></Workspace>;
}
function Model() {
  const state = useResource("/admin/model"), { t } = usePreferences();
  return <Workspace admin title="admin.model"><Resource state={state}>{data => <div className="stack-xl"><h2>{data.name}</h2><p>{data.model} · {data.version} · {data.vectorizer}</p><p className="disclaimer">{t("admin.noMedical")}</p><p>{t("result.modelLimitation")}</p><dl className="dataset-grid">{[["classes", data.classes], ["features", data.research?.features], ["train", data.research?.nTrain], ["test", data.research?.nTest], ["dataset", data.research?.dataset], ["seed", data.research?.randomState]].map(([key, value]) => <div key={key}><dt>{t(`performance.${key}`)}</dt><dd>{value ?? t("common.unavailable")}</dd></div>)}</dl><div className="metric-grid">{["accuracy", "precision", "recall", "f1"].map(key => <Metric key={key} label={t(`performance.${key}`)} value={typeof data.research?.evaluation?.[key] === "number" ? `${(data.research.evaluation[key] * 100).toFixed(2)}%` : t("common.unavailable")} />)}</div><Link href="/performance">{t("admin.modelLink")} →</Link></div>}</Resource></Workspace>;
}
function System() {
  const state = useResource("/admin/system"), { t, language } = usePreferences();
  return <Workspace admin title="admin.system"><Resource state={state}>{data => <><dl className="health-list">{["backend", "database", "ml", "modelArtifact", "shap"].map(key => <div key={key}><dt>{t(`admin.${key}`)}</dt><dd><span className={`status-dot status-dot--${data[key]}`} aria-hidden="true" />{t(`admin.${data[key]}`)}</dd></div>)}</dl><p className="small muted">{t("admin.checked")}: {displayDate(data.checkedAt, language)}</p><button className="btn btn-secondary" onClick={state.reload}>{t("dash.retry")}</button></>}</Resource></Workspace>;
}
function Logs() {
  const [page, setPage] = useState(1), [action, setAction] = useState(""), state = useResource(`/admin/audit-logs?${new URLSearchParams({ page, limit: 20, ...(action ? { action } : {}) })}`), { t, language } = usePreferences();
  return <Workspace admin title="admin.logs"><label className="field">{t("admin.action")}<select className="select" value={action} onChange={e => { setAction(e.target.value); setPage(1); }}><option value="">{t("admin.all")}</option>{["LOGIN", "LOGOUT", "ROLE_CHANGED", "USER_DISABLED", "USER_ENABLED", "ANALYSIS_CREATED", "ANALYSIS_DELETED", "REPORT_PREPARED", "SETTINGS_CHANGED", "PROFILE_CHANGED", "CONTENT_CHANGED", "ADMIN_SEEDED"].map(a => <option key={a}>{a}</option>)}</select></label><Resource state={state}>{data => <>{!data.items.length ? <Empty /> : <div className="table-scroll"><table><thead><tr>{["dash.date", "admin.action", "admin.actor", "admin.target"].map(k => <th key={k}>{t(k)}</th>)}</tr></thead><tbody>{data.items.map(row => <tr key={row._id}><td>{displayDate(row.createdAt, language)}</td><td>{row.action}</td><td className="identity-label">{row.actorUid}</td><td className="identity-label">{row.targetType}: {row.targetId}</td></tr>)}</tbody></table></div>}<Pager data={data} setPage={setPage} /></>}</Resource></Workspace>;
}
function Settings() {
  const state = useResource("/admin/settings"), { t } = usePreferences(), [change, setChange] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(false);
  async function save() { setBusy(true); setError(false); try { await platformRequest("/admin/settings", { method: "PATCH", body: { analysisEnabled: change } }); setChange(null); state.reload(); } catch { setError(true); } finally { setBusy(false); } }
  return <Workspace admin title="admin.settings"><p>{t("admin.pauseHint")}</p><Resource state={state}>{data => <label className="history-consent"><input type="checkbox" checked={data.analysisEnabled} onChange={e => setChange(e.target.checked)} />{t("admin.analysisEnabled")}</label>}</Resource><ConfirmDialog open={change !== null} title="admin.confirm" description="admin.pauseHint" busy={busy} onConfirm={save} onCancel={() => { setChange(null); setError(false); }}>{error && <p role="alert">{t("dash.saveError")}</p>}</ConfirmDialog></Workspace>;
}
function ContentEditor({ items, reload }) {
  const { t } = usePreferences(), [id, setId] = useState("platform-notice"), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
  const entry = items.find(v => v._id === id);
  async function save(e) { e.preventDefault(); const values = new FormData(e.currentTarget); setBusy(true); setNotice(""); try { await platformRequest(`/admin/content/${id}`, { method: "PUT", body: { en: { title: values.get("enTitle"), body: values.get("enBody") }, bn: { title: values.get("bnTitle"), body: values.get("bnBody") }, published: values.has("published") } }); setNotice("dash.savedNotice"); reload(); } catch { setNotice("dash.saveError"); } finally { setBusy(false); } }
  return <><label className="field">{t("admin.noticeType")}<select className="select" value={id} onChange={e => { setId(e.target.value); setNotice(""); }}>{["platform-notice", "help"].map(k => <option value={k} key={k}>{t(`admin.${k}`)}</option>)}</select></label><form key={id} className="card profile-form" onSubmit={save}><fieldset className="analysis-fields stack-xl" disabled={busy}><legend className="visually-hidden">{t("admin.content")}</legend>{["en", "bn"].map(lang => <div key={lang} lang={lang}><h2>{lang === "bn" ? "বাংলা" : "English"}</h2><label className="field">{t("admin.noticeTitle")}<input name={`${lang}Title`} className="input" maxLength={100} defaultValue={entry?.[lang].title || ""} /></label><label className="field">{t("admin.noticeBody")}<textarea name={`${lang}Body`} className="textarea" maxLength={1500} rows={5} defaultValue={entry?.[lang].body || ""} /></label></div>)}<label className="history-consent"><input name="published" type="checkbox" defaultChecked={entry?.published || false} />{t("admin.published")}</label>{notice && <p role="status">{t(notice)}</p>}<button className="btn btn-primary">{t(busy ? "dash.loading" : "dash.save")}</button></fieldset></form></>;
}
function Content() { const state = useResource("/admin/content"), { t } = usePreferences(); return <Workspace admin title="admin.content"><p className="muted">{t("admin.noticeHint")}</p><Resource state={state}>{items => <ContentEditor items={items} reload={state.reload} />}</Resource></Workspace>; }
export const ADMIN_PAGES = { users: Users, analyses: () => <History admin />, analytics: Analytics, model: Model, system: System, logs: Logs, content: Content, settings: Settings };
